# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5213cfa8833961549d561608203fb8cabddfb7e51826a3d78c2f540fd392836961f3ac7b63779d4f79f82d9e4402d2afc0e90b33398e752a00bbc82430ffa13f

test:
  secret_key_base: a0328d21bba60fd387919c19417d17665d8b35de0d183aca74cafa10e65de1e359c3ed9e3c39b82283fa93f6f91a3ecf135e57845741427de12ec65fdfdfdf14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
